services:
  # DB of POSTGRE
  ride_db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ride_hail
      - POSTGRES_USER=ride_user
      - POSTGRES_PASSWORD=hog_rider
    ports:
      - 5432:5432
    volumes:
      - ride_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  # Message Queue Rabbit
  ride_mq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  ride_data:  
  rabbitmq_data: